M48
; DRILL file {KiCad 7.0.5-0} date 2023 October 09, Monday 15:45:43
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-09T15:45:43-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.700
%
G90
G05
T1
X148.73Y-92.725
X150.0Y-92.725
X151.27Y-92.725
T2
X147.46Y-92.725
X152.54Y-92.725
T0
M30
